name: Django Testing and Deploy


on:
  push:
    branches: [cooo]

jobs:
  tests:
    runs-on: ubuntu-20.04
    env:
      DB_USER: ${{ secrets.DB_USER }}
      DEBUG: ${{ secrets.DEBUG }}
      DB_ENGINE: ${{ secrets.DB_ENGINE }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_NAME: ${{ secrets.DB_NAME }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
    services:
      postgres_main:
        image: postgres:12
        env:
          DB_USER: ${{ env.DB_USER }}
          DB_PASSWORD: ${{ env.DB_PASSWORD }}
          DB_NAME: ${{ env.DB_NAME }}
        ports:
          - 5432:5432
        options:
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Проверяем репозиторий на наличие изменений
        uses: actions/checkout@v3

      - name: Установка python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Установка библиотек
        run: pip install -r requirements.txt

      - name: Линтинг кода
        run: flake8 .\logistic\ --exclude=logistic.\migrations    

      - name: Тестинг
        run: python manage.py test
        env:
          SECRET_KEY: ${{ env.SECRET_KEY }}
          DEBUG: "0"
          ALLOWED_HOSTS: ${{ env.ALLOWED_HOSTS }}
          DB_NAME: ${{ env.DB_NAME }}
          DB_USER: ${{ env.DB_USER }}
          DB_PASSWORD: ${{ env.DB_PASSWORD }}
          DB_HOST: ${{ env.DB_HOST }}
          DB_PORT: ${{ env.DB_PORT }}

#      - name: Деплой
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.HOST }}
#          username: ${{ secrets.USERNAME }}
#          password: ${{ secrets.PASSWORD }}
#          script: expect /home/adilet/url_shortener/pull.exp
